### ISSUE TITLE
twitter-time-tooltip.user.js

### ISSUE THREAD

**Issue by Machou** [chocolateboy/userscripts#10] opened 2020-06-27 15:04 UTC
Hello

Script **twitter-time-tooltip.user.js** don't work
[Screenshot](https://i.ibb.co/nMdszFK/1.jpg)

Script **twitter-reply-count.user.js**
with the new interface, useless; because Twitter write how much reply now !

Firefox 77.0.1
Windows 7
GS 4.9
**new interface twitter june 2020**

**Comment by chocolateboy** [comment] 2020-06-27 16:24
> Script twitter-time-tooltip.user.js don't work

I'm not sure what that screenshot is supposed to demonstrate, since it appears to include a tooltip, albeit not the one provided by this script, but I can't reproduce this with Greasemonkey 4.9 / Firefox 77.0.1 / Linux. Try to reproduce it in a clean profile.

>  with the new interface, useless; because Twitter write how much reply now !

Not sure what this means. The number of replies is shown in timelines, but not shown on the tweet page in the new interface, at least not for [me](https://greasyfork.org/system/screenshots/screenshots/000/021/654/original/twitter-reply-count-before.png) (or [archive.today](https://archive.is/WtdSZ)).

It *is* displayed (in a separate row) for the [archive.org](https://web.archive.org/web/20190718050524/https://twitter.com/TwitterSupport/status/1150813610370748416) bot. Do you have a custom user-agent set for Twitter (e.g. still using an ["Old Twitter"](https://github.com/ZusorCode/GoodTwitter) addon/userscript)?

If you can see the number of replies on [that tweet](https://twitter.com/TwitterSupport/status/1150813610370748416) without this userscript, feel free to post a screenshot.

**Comment by Machou** [comment] 2020-06-27 18:13
I have try with new profile, but i have the same "popup" by default. A standard popup title on a href=""

And about the comment, yes i understand now :)

**Comment by chocolateboy** [comment] 2020-06-27 18:41
> i have the same "popup" by default.

Could be a locale thing. I've tested foreign interface *languages* (e.g. French), but don't know how the site renders when accessed from a foreign *location* (e.g. France).

Either way, closing this as "this already works in my location/locale" is not something I've been able to reproduce and not a bug (if the feature isn't missing, there's no reason to [use the script](https://github.com/chocolateboy/userscripts/blob/35a008324c9b82c31cf70a9364c42a2a1f33d56d/src/twitter-time-tooltip.user.js#L3)):

> **Restore** timestamp tooltips when hovering over post dates on Twitter

**Comment by Machou** [comment] 2020-06-27 20:36
where did you put you title ? on the <a href ? or <time ?

I have make a new [screenshot](https://i.ibb.co/345xX91/Sans-titre-2.jpg)

i'm on fr_FR

**Comment by chocolateboy** [comment] 2020-06-27 21:03
> where did you put you title ? on the <a href ? or <time ?

On the link (the `<a></a>` element), but that's not the title added by my script. My title contains a [hyphen](https://github.com/chocolateboy/userscripts/blob/35a008324c9b82c31cf70a9364c42a2a1f33d56d/src/twitter-time-tooltip.user.js#L32) and uses the default locale (English).

> if i activate the extension, i have the popup time, and if i disable, i have the time too.

I've just checked, and you're right! They've brought the tooltip back in the last few days:

```html
<a href="..." title="12:33 AM · Jun 26, 2020"><time datetime="2020-06-26T00:33:54.000Z">Jun 26</time></a>
```

Thanks, I'll remove the script as it's no longer needed.

**Comment by chocolateboy** [comment] 2020-06-27 21:29
Looks like there's no specific date where the tooltips were restored. Sometimes they're present, e.g.:

- [17th June](https://archive.is/57OGJ)
- [25th May](https://archive.is/eAJxN)

Somtimes they're not:

- [11th June](https://archive.is/Kcahc)
- [10th June](https://archive.is/6q6rO)

I'm gonna keep it for now to add the tooltip for cases when (if) they're missing.

**Closed** 2020-06-27 22:34 UTC
